name: Build
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Change File
      run: sh ./appendLine.sh
    - name: Commit File
      run: |
        git add .
        git commit -m "Changed File"
        git push origin develop